name: VehiclesPickupAddon
version: ${project.version}
main: tk.nimari.VehiclesPickupAddon
api-version: 1.14
depend: [Vehicles]
authors: [Nimāri]
description: An addon made for the Minecraft Vehicles plugin that allows for toggling of vehicle pickup.