name: VehiclesPickupAddon
version: ${project.version}
main: jp.marisa.VehiclesPickupAddon
api-version: 1.18
depend: [ Vehicles ]
authors: [Marisa]
description: An addon made for the Vehicles plugin that allows for toggling of vehicle pickup.